site_name: IXP Manager Documentation
site_url: https://docs.ixpmanager.org
repo_url: https://github.com/inex/ixp-manager-docs-md
edit_uri: edit/master/docs
theme: readthedocs
repo_name: GitHub
copyright: '&copy; 2017-2018, Internet Neutral Exchange Association Company Limited by Guarantee (INEX).<br><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by-sa/4.0/80x15.png" /></a>&nbsp;This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.'
pages:
- Home: 'index.md'
- Installation:
    - 'Introduction': 'install/index.md'
    - 'Automated Script': 'install/automated-script.md'
    - 'Maintenance Mode': 'install/maint-mode.md'
    - 'Manual Installation': 'install/manually.md'
    - 'Upgrading': 'install/upgrading.md'
    - 'Upgrade From v3': 'install/upgrade-v3.md'
    - 'Runtime Configuration': 'install/runtime.md'
- General Usage:
    - 'Customers / Members': 'usage/customers.md'
    - 'Customer Notes': 'usage/customer-notes.md'
    - 'Customer Connections': 'usage/interfaces.md'
    - 'Users & Contacts': 'usage/users.md'
- Features:
    - 'API': 'features/api.md'
    - 'AS112': 'features/as112.md'
    - 'Console Servers': 'features/console-servers.md'
    - 'Contact Groups': 'features/contact-groups.md'
    - 'Cross Connects': 'features/patch-panels.md'
    - 'DNS / ARPA': 'features/dns-arpa.md'
    - 'Grapher': 'grapher/introduction.md'
    - 'Helpdesk Integration': 'features/helpdesk.md'
    - 'IRRDB': 'features/irrdb.md'
    - 'IX-F Member Export': 'features/ixf-export.md'
    - 'MAC Addresses': 'features/layer2-addresses.md'
    - 'Looking Glass': 'features/looking-glass.md'
    - 'MAC Addresses': 'features/layer2-addresses.md'
    - 'Member Export': 'features/member-export.md'
    - 'Mailing List Management': 'features/mailing-lists.md'
    - 'Nagios': 'features/nagios.md'
    - 'Patch Panels': 'features/patch-panels.md'
    - 'Reseller Functionality': 'features/reseller.md'
    - 'Route Collectors': 'features/route-collectors.md'
    - 'Route Servers': 'features/route-servers.md'
    - 'Router Configuration': 'features/routers.md'
    - 'Skinning': 'features/skinning.md'
    - 'Smokeping': 'grapher/smokeping.md'
    - 'Static Content': 'features/static-content.md'
    - 'TACACS': 'features/tacacs.md'
- Grapher:
    - 'Introduction': 'grapher/introduction.md'
    - 'API &amp; Permissions': 'grapher/api.md'
    - 'Backend: MRTG': 'grapher/mrtg.md'
    - 'Backend: sflow': 'grapher/sflow.md'
    - 'Backend: Smokeping': 'grapher/smokeping.md'
- 'Sflow Support':
    - 'Introduction': 'features/sflow.md'
    - 'Peer-to-peer Graphs': 'features/sflow-p2p.md'
- Development:
    - 'API': 'dev/api.md'
    - 'Continuous Integration': 'dev/ci.md'
    - 'Contributer License Agreement': 'dev/cla.md'
    - 'Docker': 'dev/docker.md'
    - 'Documentation': 'dev/docs.md'
    - 'Forms': 'dev/forms.md'
    - 'Frontend CRUD': 'dev/frontend-crud.md'
    - 'Grapher': 'dev/grapher.md'
    - 'Helpers': 'dev/helpders.md'
    - 'Looking Glass': 'dev/looking-glass.md'
    - 'Release Procedure': 'dev/release-procedure.md'
    - 'Vagrant': 'dev/vagrant.md'
markdown_extensions:
  - pymdownx.superfences
  - toc:
      permalink: ÔÉÅ
