site_name: IXP Manager
theme: readthedocs
repo_name: GitHub
copyright: '&copy; 2017, Internet Neutral Exchange Association Company Limited by Guarantee (INEX)'
pages:
- Home: 'index.md'
- Installation:
    - 'Introduction': 'install/index.md'
    - 'Automated Script': 'install/automated-script.md'
    - 'Maintenance Mode': 'install/maint-mode.md'
    - 'Manual Installation': 'install/manually.md'
    - 'Upgrading': 'install/upgrading.md'
    - 'Upgrade From v3': 'install/upgrade-v3.md'
- Features:
    - 'AS112': 'features/routers.md'
    - 'Contact Groups': 'features/contact-groups.md'
    - 'Cross Connects': 'features/patch-panels.md'
    - 'Grapher': 'features/grapher.md'
    - 'Helpdesk Integration': 'features/helpdesk.md'
    - 'IRRDB': 'features/routers.md'
    - 'Layer2 Addresses': 'features/layer2-addresses.md'
    - 'Looking Glass': 'features/looking-glass.md'
    - 'MAC Addresses': 'features/layer2-addresses.md'
    - 'Patch Panels': 'features/patch-panels.md'
    - 'Route Collector': 'features/routers.md'
    - 'Route Server': 'features/routers.md'
    - 'Routers': 'features/routers.md'
    - 'Skinning': 'features/skinning.md'
- Development:
    - 'API': 'dev/api.md'
    - 'Documentation': 'dev/docs.md'
    - 'Grapher': 'dev/grapher.md'
    - 'Helpers': 'dev/helpders.md'
    - 'Vagrant': 'dev/vagrant.md'
